<?xml version="1.0" encoding="utf-8"?><Database Name="OrderingSystem" Class="DatabaseEntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=atirtahir;Initial Catalog=OrderingSystem;Integrated Security=True" SettingsObjectName="GroupDocs.AssemblyExamples.ProjectEntities.Properties.Settings" SettingsPropertyName="OrderingSystemConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ShippingAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CustomerContactNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="CustomerID" OtherKey="CustomerID" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.ProductOrder" Member="ProductOrders">
    <Type Name="ProductOrder">
      <Column Name="ProductOrderID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="ProductQuantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Order_ProductOrder" Member="Order" ThisKey="OrderID" OtherKey="OrderID" Type="Order" IsForeignKey="true" />
      <Association Name="Product_ProductOrder" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="OrderID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ShippingDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Order_ProductOrder" Member="ProductOrders" ThisKey="OrderID" OtherKey="OrderID" Type="ProductOrder" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProductPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UnitsInStock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Discount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Product_ProductOrder" Member="ProductOrders" ThisKey="ProductID" OtherKey="ProductID" Type="ProductOrder" />
    </Type>
  </Table>
</Database>